sudo: false
git:
  depth: 10
branches:
  only:
    - master
    - next
language: node_js
cache:
  directories:
    - $HOME/.npm
    - node_modules
matrix:
  include:
    - node_js: '11'
      script: npm run ci:lint
      env: JOB_PART=lint
    - node_js: '11'
      script: npm run ci:coverage
      env: JOB_PART=coverage
    - node_js: '10'
      script: npm run ci:test
      env: JOB_PART=test
    - node_js: '8'
      script: npm run ci:test
      env: JOB_PART=test
    - node_js: '6'
      script: npm run ci:test
      env: JOB_PART=test
before_install:
  - npm install -g npm@latest
install:
  - npm ci
before_script:
  - node --version
  - npm --version
script:
  - npm run ci:$JOB_PART
after_success:
  - if [ "$JOB_PART" = "coverage" ]; then bash <(curl -s https://codecov.io/bash); fi
